// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjqmnqpedlrbupwisybj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqcW1ucXBlZGxyYnVwd2lzeWJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0ODUwODQsImV4cCI6MjA2MTA2MTA4NH0.pem3Quk3fqHmjZXXGpM5dkkctttGuJ5EyFHHqpEpsDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);